### ISSUE TITLE
Crash when text starts with `---`

### ISSUE THREAD

**Issue by amadeu01** [viniciusaro/SwiftMarkdown#2]
When we attempt to create a new `SwiftyMarkdown` using one string that starts with the characters `---` it will break.
It does not happen if you have something before the `---`, such as `. ---`

How we are currently using the lib  ⤵️
```swift
            let markDown = SwiftyMarkdown(string: text)
            self.descriptionLabel.attributedText = markDown.attributedString()
```

It might be related to ⤵️

```
static public var frontMatterRules = [
		FrontMatterRule(openTag: "---", closeTag: "---", keyValueSeparator: ":")
	]
```

**Comment by viniciusaro** [comment]
Hey @amadeu01, sorry for the late reply. Were you able to solve the issue?
